"""Коммерческие услуги и AI-решения портала ДИС."""

PRODUCTS = [
    {
        "slug": "elan",
        "name": "ÉLAN — сайт косметологического кабинета",
        "price": None,
        "price_label": "от 24 900 ₽",
        "summary": "Готовый адаптивный MVP с услугами, ценами, FAQ и онлайн-записью. Адаптируется под бренд, специалистов и процессы конкретного кабинета.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "adapted",
        "service_class_label": "Готовое Web-решение с адаптацией",
        "delivery_label": "от 7–10 рабочих дней",
    },
    {
        "slug": "express-review",
        "name": "Экспресс-разбор",
        "price": 4900,
        "price_label": "4 900 ₽",
        "summary": "Разбор задачи, рекомендации и план следующих шагов.",
        "payment_object": "service",
        "sellable": True,
        "service_class": "fixed",
        "service_class_label": "Готовая услуга",
        "delivery_label": "до 3 рабочих дней",
    },
    {
        "slug": "ai-audit",
        "name": "AI-аудит процесса",
        "price": 14900,
        "price_label": "14 900 ₽",
        "summary": "Разбор процесса, точки автоматизации, архитектура и дорожная карта.",
        "payment_object": "service",
        "sellable": True,
        "service_class": "fixed",
        "service_class_label": "Готовая услуга",
        "delivery_label": "до 5 рабочих дней",
    },
    {
        "slug": "meeting-intelligence",
        "name": "Meeting Intelligence",
        "price": 19900,
        "price_label": "19 900 ₽",
        "summary": "Настройка рабочего контура для расшифровки встреч, решений и задач.",
        "payment_object": "service",
        "sellable": True,
        "service_class": "fixed",
        "service_class_label": "Готовая услуга",
        "delivery_label": "до 7 рабочих дней",
    },
    {
        "slug": "reputation-assistant",
        "name": "Reputation Assistant",
        "price": 24900,
        "price_label": "24 900 ₽",
        "summary": "Анализ отзывов, проекты ответов и контроль человеком.",
        "payment_object": "service",
        "sellable": True,
        "service_class": "fixed",
        "service_class_label": "Готовая услуга",
        "delivery_label": "до 7 рабочих дней",
    },
    {
        "slug": "knightcat-content-factory",
        "name": "KnightCat Content Factory",
        "price": 29900,
        "price_label": "29 900 ₽",
        "summary": "Контент-завод: идея → тексты → изображение → согласование → публикация.",
        "payment_object": "service",
        "sellable": True,
        "service_class": "fixed",
        "service_class_label": "Готовая услуга",
        "delivery_label": "до 10 рабочих дней",
    },
    {
        "slug": "kpi-pulse",
        "name": "KPI-Pulse / AI-аналитика",
        "price": None,
        "price_label": "от 29 900 ₽",
        "summary": "Сбор показателей, автоматизация отчётности и понятные управленческие сводки.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "adapted",
        "service_class_label": "Готовое AI-решение с адаптацией",
        "delivery_label": "от 10 рабочих дней",
    },
    {
        "slug": "telegram-bot-mvp",
        "name": "Telegram-бот MVP",
        "price": None,
        "price_label": "от 29 900 ₽",
        "summary": "Рабочий Telegram-бот под конкретный бизнес-процесс с базовой автоматизацией.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "adapted",
        "service_class_label": "Готовое AI-решение с адаптацией",
        "delivery_label": "от 10 рабочих дней",
    },
    {
        "slug": "onboardflow-ai",
        "name": "OnboardFlow-AI",
        "price": None,
        "price_label": "от 39 900 ₽",
        "summary": "AI-онбординг сотрудников по проверенной корпоративной базе знаний.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "adapted",
        "service_class_label": "Готовое AI-решение с адаптацией",
        "delivery_label": "от 10 рабочих дней",
    },
    {
        "slug": "docpulse-ai",
        "name": "DocPulse-AI",
        "price": None,
        "price_label": "от 39 900 ₽",
        "summary": "Структурированный разбор документов и PDF с выводами и навигацией по источникам.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "adapted",
        "service_class_label": "Готовое AI-решение с адаптацией",
        "delivery_label": "от 10 рабочих дней",
    },
    {
        "slug": "rag-documents",
        "name": "RAG по документам",
        "price": None,
        "price_label": "от 49 900 ₽",
        "summary": "Поиск и ответы по собственной базе документов с цитированием источников.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "custom",
        "service_class_label": "AI-решение под ключ",
        "delivery_label": "от 20 рабочих дней",
    },
    {
        "slug": "ai-assistant-integrations",
        "name": "AI-ассистент с интеграциями",
        "price": None,
        "price_label": "от 59 900 ₽",
        "summary": "AI-ассистент с подключением API, CRM, баз данных, Telegram и рабочих сервисов.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "custom",
        "service_class_label": "AI-решение под ключ",
        "delivery_label": "от 15 рабочих дней",
    },
    {
        "slug": "autosfera-ai",
        "name": "AutoSfera AI / автоматизация продаж",
        "price": None,
        "price_label": "от 79 900 ₽",
        "summary": "Мультиагентный контур продаж и сервиса: маршрутизация, база знаний, CRM и передача оператору.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "custom",
        "service_class_label": "AI-решение под ключ",
        "delivery_label": "от 20–30 рабочих дней",
    },
    {
        "slug": "custom-ai",
        "name": "Custom AI / мультиагентная система",
        "price": None,
        "price_label": "от 99 900 ₽",
        "summary": "RAG, агенты, CRM, интеграции, базы данных и несколько каналов под конкретный процесс.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "custom",
        "service_class_label": "AI-решение под ключ",
        "delivery_label": "от 20–30 рабочих дней",
    },
    {
        "slug": "support",
        "name": "Поддержка и развитие",
        "price": None,
        "price_label": "от 9 900 ₽/мес",
        "summary": "Поддержка работающего решения, небольшие изменения, контроль и консультации.",
        "payment_object": "service",
        "sellable": False,
        "service_class": "support",
        "service_class_label": "Сопровождение",
        "delivery_label": "ежемесячно",
    },
]

PRODUCTS_BY_SLUG = {item["slug"]: item for item in PRODUCTS}
